name: poisson_disc
version: 1.0.0
author: Gary Smith <argentiapparatus@gmail.com>
description: Poisson disc distribution implementation using the Bridson algorithm.
homepage: https://github.com/argentiapparatus/poisson_disc
environment:
  sdk: '>=1.9.0'
dependencies:
  vector_math: '>=1.4.3 <2.0.0'
