name: poisson_disc
version: 2.0.0
author: Gary Smith <argentiapparatus@gmail.com>
description: Poisson disc point distribution implementations.
homepage: https://github.com/argentiapparatus/poisson_disc
environment:
  sdk: '>=1.9.1 <2.0.0'
dependencies:
  vector_math: '^1.4.3'
dev_dependencies:
  browser: '^0.10.0'
  regular_grid: '^0.1.0'
  test: '^0.12.5'
